### ISSUE TITLE
qavhwdevice_d3d11.cpp is missing a include for libavcodec/avcodec.h

### ISSUE THREAD

**Issue by TyrasNistru** [valbok/QtAVPlayer#393]
Without it, It doesn't build on Qt 6.5.2 With MSVC 2019, with the following errors:

```
..\..\..\..\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11.cpp(36): error C2027: use of undefined type 'AVCodecContext'
D:\Users\mrfis\Development\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11_p.h(26): note: see declaration of 'AVCodecContext'
..\..\..\..\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11.cpp(38): error C2027: use of undefined type 'AVCodecContext'
D:\Users\mrfis\Development\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11_p.h(26): note: see declaration of 'AVCodecContext'
..\..\..\..\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11.cpp(35): error C3861: 'avcodec_get_hw_frames_parameters': identifier not found
..\..\..\..\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11.cpp(45): error C2027: use of undefined type 'AVCodecContext'
D:\Users\mrfis\Development\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11_p.h(26): note: see declaration of 'AVCodecContext'
..\..\..\..\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11.cpp(46): error C3536: 'frames_ctx': cannot be used before it is initialized
..\..\..\..\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11.cpp(47): error C3536: 'hwctx': cannot be used before it is initialized
..\..\..\..\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11.cpp(49): error C2027: use of undefined type 'AVCodecContext'
D:\Users\mrfis\Development\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11_p.h(26): note: see declaration of 'AVCodecContext'
..\..\..\..\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11.cpp(52): error C2027: use of undefined type 'AVCodecContext'
D:\Users\mrfis\Development\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11_p.h(26): note: see declaration of 'AVCodecContext'
```

adding `#include <libavcodec/avcodec.h>` right below `#include <libavutil/hwcontext_d3d11va.h>` solves this.

**Comment by valbok** [comment]
Hi, thanks for the contribution, if you would add the PR, it would be even better *-)

Btw, it looks like related to ffmpeg ver, since never seen this before. What version do you use?

**Comment by bobrokrol** [comment]
> Hi, thanks for the contribution, if you would add the PR, it would be even better *-)
> 
> Btw, it looks like related to ffmpeg ver, since never seen this before. What version do you use?

I have similar errors, but this
`#include <libavcodec/avcodec.h> right below #include <libavutil/hwcontext_d3d11va.h>`
fix only few of them and I getting other errors.
|
What version of QT ( MinGV / Visual studio)  and what version of ffmpeg must be used on Windows to comile example?
I'd like to use perecompiled ffmpeg libraries 
https://github.com/BtbN/FFmpeg-Builds/releases
What exactly must be used to compile and run the sample?

**Comment by valbok** [comment]
Thanks, I took from there https://github.com/BtbN/FFmpeg-Builds/releases, and it really fails.

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/pull/396

**Comment by bobrokrol** [comment]
> Thanks, I took from there https://github.com/BtbN/FFmpeg-Builds/releases, and it really fails.

I have similar errors with different ffmeg versions and QT
Right now Im using qt 6.5.2
and ffmpeg-n6.0-11-g3980415627-win64-lgpl-shared-6.0, downloaded from BtbN repo.
But the problem was in missed headers  I had to update

`PRIVATE_HEADERS += \
    $$PWD/qavcodec_p.h \
    $$PWD/qavcodec_p_p.h \
    $$PWD/qavframecodec_p.h \
    $$PWD/qavaudiocodec_p.h \
    $$PWD/qavvideocodec_p.h \
    $$PWD/qavsubtitlecodec_p.h \
    $$PWD/qavhwdevice_p.h \
    $$PWD/qavdemuxer_p.h \
    $$PWD/qavpacket_p.h \
    $$PWD/qavstreamframe_p.h \
    $$PWD/qavframe_p.h \
    $$PWD/qavpacketqueue_p.h \
    $$PWD/qavvideobuffer_p.h \
    $$PWD/qavvideobuffer_cpu_p.h \
    $$PWD/qavvideobuffer_gpu_p.h \
    $$PWD/qavfilter_p.h \
    $$PWD/qavfilter_p_p.h \
    $$PWD/qavvideofilter_p.h \
    $$PWD/qavaudiofilter_p.h \
    $$PWD/qavfiltergraph_p.h \
    $$PWD/qavinoutfilter_p.h \
    $$PWD/qavinoutfilter_p_p.h \
    $$PWD/qavvideoinputfilter_p.h \
    $$PWD/qavaudioinputfilter_p.h \ 
    $$PWD/qavvideooutputfilter_p.h \
    $$PWD/qavaudiooutputfilter_p.h \
    $$PWD/qaviodevice_p.h \
    $$PWD/qavfilters_p.h \
    $$PWD/qavaudiooutput.h \
    $$PWD/qavandroidsurfacetexture.h

PUBLIC_HEADERS += \
    $$PWD/qavaudioformat.h \
    $$PWD/qavstreamframe.h \
    $$PWD/qavframe.h \
    $$PWD/qavvideoframe.h \
    $$PWD/qavaudioframe.h \
    $$PWD/qavsubtitleframe.h \
    $$PWD/qtavplayerglobal.h \
    $$PWD/qavstream.h \
    $$PWD/qavplayer.h \

SOURCES += \
    $$PWD/qavplayer.cpp \
    $$PWD/qavcodec.cpp \
    $$PWD/qavframecodec.cpp \
    $$PWD/qavaudiocodec.cpp \
    $$PWD/qavvideocodec.cpp \
    $$PWD/qavsubtitlecodec.cpp \
    $$PWD/qavdemuxer.cpp \
    $$PWD/qavpacket.cpp \
    $$PWD/qavframe.cpp \
    $$PWD/qavstreamframe.cpp \
    $$PWD/qavvideoframe.cpp \
    $$PWD/qavaudioframe.cpp \
    $$PWD/qavsubtitleframe.cpp \
    $$PWD/qavvideobuffer_cpu.cpp \
    $$PWD/qavvideobuffer_gpu.cpp \
    $$PWD/qavfilter.cpp \
    $$PWD/qavvideofilter.cpp \
    $$PWD/qavaudiofilter.cpp \
    $$PWD/qavfiltergraph.cpp \
    $$PWD/qavinoutfilter.cpp \
    $$PWD/qavvideoinputfilter.cpp \
    $$PWD/qavaudioinputfilter.cpp \
    $$PWD/qavvideooutputfilter.cpp \
    $$PWD/qavaudiooutputfilter.cpp \
    $$PWD/qaviodevice.cpp \
    $$PWD/qavstream.cpp \
    $$PWD/qavfilters.cpp \
    $$PWD/qavaudiooutput.cpp \`
    
    and also was some errors about incopatible "<<" overloading in qavhwdevice_d3d11.cpp
   
    so  I had to manually do convertion to QString    
`     qWarning() << "Failed to obtain resource handle from FFmpeg texture:" << hr <<  QString::fromStdString(std::system_category().message(hr));`

Right now it compiles and runs after I manually copied all .dlls to output folder

**Comment by valbok** [comment]
Thanks, I just tested 6.5.2 and it works, but 6.4 does not, are you sure that you use 6.5?
