### ISSUE TITLE
Feature request: Qt 5.12 support

### ISSUE THREAD

**Issue by ElderOrb** [valbok/QtAVPlayer#4]
What would it take to add Qt 5.12 support?

**Comment by valbok** [comment]
Added some minor fixes to build against 5.12 on linux, 
did not test rest, also did not test how HW acceleration works with it.

**Comment by ElderOrb** [comment]
Great! I will check.

**Comment by ElderOrb** [comment]
Hmmm...

```
ai@ELDERORB:~/Projects/QtAVPlayer$ qmake
Info: creating cache file /home/ai/Projects/QtAVPlayer/.qmake.cache

Running configuration tests...
Done running configuration tests.

Configure summary:

Qt AVPlayer:
  FFmpeg ................................. yes
  va_x11 ................................. no
  va_drm ................................. no

Qt is now configured for building. Just run 'make'.
Once everything is built, you must run 'make install'.
Qt will be installed into '/home/ai/Qt/5.12.10/gcc_64'.

Prior to reconfiguration, make sure you remove any leftovers from
the previous build.

ai@ELDERORB:~/Projects/QtAVPlayer$ make
cd src/ && ( test -e Makefile || /home/ai/Qt/5.12.10/gcc_64/bin/qmake -o Makefile /home/ai/Projects/QtAVPlayer/src/src.pro ) && make -f Makefile
make[1]: Entering directory '/home/ai/Projects/QtAVPlayer/src'
cd avplayer/ && ( test -e Makefile || /home/ai/Qt/5.12.10/gcc_64/bin/qmake -o Makefile /home/ai/Projects/QtAVPlayer/src/avplayer/avplayer.pro ) && make -f Makefile
Project MESSAGE: perl -w /home/ai/Qt/5.12.10/gcc_64/bin/syncqt.pl -module QtAVPlayer -version 6.0.0 -outdir /home/ai/Projects/QtAVPlayer -builddir /home/ai/Projects/QtAVPlayer /home/ai/Projects/QtAVPlayer
<srcbase> = /home/ai/Projects/QtAVPlayer
<bldbase> = /home/ai/Projects/QtAVPlayer
<outbase> = /home/ai/Projects/QtAVPlayer
QtAVPlayer: created fwd-include header(s) for <srcbase>/src/avplayer/ { qavaudiocodec_p.h (1), qavaudioframe_p.h (1), qavaudiooutput.h (2), qavcodec_p.h (1), qavcodec_p_p.h (1), qavdemuxer_p.h (1), qavframe_p.h (1), qavframe_p_p.h (1), qavhwdevice_d3d11_p.h (1), qavhwdevice_mediacodec_p.h (1), qavhwdevice_p.h (1), qavhwdevice_vaapi_drm_egl_p.h (1), qavhwdevice_vaapi_x11_glx_p.h (1), qavhwdevice_videotoolbox_p.h (1), qavpacket_p.h (1), qavpacketqueue_p.h (1), qavplanarvideobuffer_cpu_p.h (1), qavplanarvideobuffer_gpu_p.h (1), qavplayer.h (2), qavvideocodec_p.h (1), qavvideoframe_p.h (1), qtavplayerglobal.h (1), qtavplayerglobal_p.h (1) }
QtAVPlayer: created version header
QtAVPlayer: created master header
QtAVPlayer: created headers.pri file
make[2]: Entering directory '/home/ai/Projects/QtAVPlayer/src/avplayer'
perl /home/ai/Qt/5.12.10/gcc_64/mkspecs/features/data/unix/findclasslist.pl < QtAVPlayer.version.in > QtAVPlayer.version
g++ -pipe -O2 -g -std=c++1y -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -W -Wvla -Wdate-time -D_REENTRANT -fPIC -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_AVPLAYER_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -D_REENTRANT -I. -I../../include -I../../include/QtAVPlayer -I../../include/QtAVPlayer/6.0.0 -I../../include/QtAVPlayer/6.0.0/QtAVPlayer -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimedia/5.12.10 -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimedia/5.12.10/QtMultimedia -I/home/ai/Qt/5.12.10/gcc_64/include -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimedia -I/home/ai/Qt/5.12.10/gcc_64/include/QtNetwork -I/home/ai/Qt/5.12.10/gcc_64/include/QtGui/5.12.10 -I/home/ai/Qt/5.12.10/gcc_64/include/QtGui/5.12.10/QtGui -I/home/ai/Qt/5.12.10/gcc_64/include/QtGui -I/home/ai/Qt/5.12.10/gcc_64/include/QtConcurrent -I/home/ai/Qt/5.12.10/gcc_64/include/QtCore/5.12.10 -I/home/ai/Qt/5.12.10/gcc_64/include/QtCore/5.12.10/QtCore -I/home/ai/Qt/5.12.10/gcc_64/include/QtCore -I.moc -isystem /usr/include/libdrm -isystem /usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/home/qt/openssl-1.1.1g/include -I/home/ai/Qt/5.12.10/gcc_64/mkspecs/linux-g++ -x c++-header -c ../../include/QtAVPlayer/QtAVPlayerDepends -o .pch/Qt5AVPlayer.gch/c++
g++ -c -include .pch/Qt5AVPlayer -pipe -O2 -g -std=c++1y -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -W -Wvla -Wdate-time -D_REENTRANT -fPIC -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_AVPLAYER_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -D_REENTRANT -I. -I../../include -I../../include/QtAVPlayer -I../../include/QtAVPlayer/6.0.0 -I../../include/QtAVPlayer/6.0.0/QtAVPlayer -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimedia/5.12.10 -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimedia/5.12.10/QtMultimedia -I/home/ai/Qt/5.12.10/gcc_64/include -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimedia -I/home/ai/Qt/5.12.10/gcc_64/include/QtNetwork -I/home/ai/Qt/5.12.10/gcc_64/include/QtGui/5.12.10 -I/home/ai/Qt/5.12.10/gcc_64/include/QtGui/5.12.10/QtGui -I/home/ai/Qt/5.12.10/gcc_64/include/QtGui -I/home/ai/Qt/5.12.10/gcc_64/include/QtConcurrent -I/home/ai/Qt/5.12.10/gcc_64/include/QtCore/5.12.10 -I/home/ai/Qt/5.12.10/gcc_64/include/QtCore/5.12.10/QtCore -I/home/ai/Qt/5.12.10/gcc_64/include/QtCore -I.moc -isystem /usr/include/libdrm -isystem /usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/home/qt/openssl-1.1.1g/include -I/home/ai/Qt/5.12.10/gcc_64/mkspecs/linux-g++ -o .obj/qavaudiooutput.o qavaudiooutput.cpp
qavaudiooutput.cpp:13:10: fatal error: libavutil/time.h: No such file or directory
 #include "libavutil/time.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1936: recipe for target '.obj/qavaudiooutput.o' failed
make[2]: *** [.obj/qavaudiooutput.o] Error 1
make[2]: Leaving directory '/home/ai/Projects/QtAVPlayer/src/avplayer'
Makefile:46: recipe for target 'sub-avplayer-make_first' failed
make[1]: *** [sub-avplayer-make_first] Error 2
make[1]: Leaving directory '/home/ai/Projects/QtAVPlayer/src'
Makefile:48: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2
```

ai@ELDERORB:~/Projects/QtAVPlayer$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

WSL

**Comment by ElderOrb** [comment]
Maybe because ffmpeg installed without pkg-config support... Any ideas where can I find right ffmpeg for ubuntu 18?

**Comment by valbok** [comment]
FFmpeg ................................. yes

shows that it is visible using pkg-config
btw what is the version ?

$ pkg-config --version libavutil 
0.29.1

**Comment by ElderOrb** [comment]
ai@ELDERORB:~/Projects/QtAVPlayer$ pkg-config --version libavutil
0.29.1

weird. will do completely clean build

**Comment by ElderOrb** [comment]
Okay, I see... With a completely clean build: 

ai@ELDERORB:~/Projects/QtAVPlayer-upstream$ qmake
Info: creating stash file /home/ai/Projects/QtAVPlayer-upstream/.qmake.stash
Info: creating cache file /home/ai/Projects/QtAVPlayer-upstream/.qmake.cache

Running configuration tests...
Checking for FFmpeg... no
Checking for va_drm... no
Checking for va_x11... no
Done running configuration tests.

Configure summary:

Qt AVPlayer:
  FFmpeg ................................. no
  va_x11 ................................. no
  va_drm ................................. no

Qt is now configured for building. Just run 'make'.
Once everything is built, you must run 'make install'.
Qt will be installed into '/home/ai/Qt/5.12.10/gcc_64'.

Prior to reconfiguration, make sure you remove any leftovers from
the previous build.


... which means previous one was 'pre-configured' because I didn't clean it completely from my experiments with QtAVPlayer (where I passed FFMPEG path via environment variable). 

So, seems like my ffmpeg version doesn't have related *.pc files. Google-ing atm, but seems like its not so easy to find right pkg-config-friendly ffmpeg for ubuntu 18.04....

**Comment by ElderOrb** [comment]
Built ffmpeg manually with './configure --enable-shared --disable-static --disable-asm'

now QtAVPlayer refuse to link: 

/usr/bin/ld: /usr/local/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32 against symbol `ff_pw_9' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value

**Comment by ElderOrb** [comment]
Okay, after resolving stupid issues with ffmpeg I QtAVPlayer compiled successfully for 5.12.10. 

But then I tried to build example: 

ai@ELDERORB:~/Projects/QtAVPlayer-upstream/examples/qml_video$ make
g++ -c -pipe -O2 -g -fno-exceptions -Wall -W -D_REENTRANT -fPIC -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_AVPLAYER_LIB -DQT_QTMULTIMEDIAQUICKTOOLS_LIB -DQT_MULTIMEDIA_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -D_REENTRANT -I. -I. -I../../include -I../../include/QtAVPlayer -I/home/ai/Qt/5.12.10/gcc_64/include -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimediaQuick -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimediaQuick/5.12.10 -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimediaQuick/5.12.10/QtMultimediaQuick -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimedia/5.12.10 -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimedia/5.12.10/QtMultimedia -I/home/ai/Qt/5.12.10/gcc_64/include/QtMultimedia -I/home/ai/Qt/5.12.10/gcc_64/include/QtQuick -I/home/ai/Qt/5.12.10/gcc_64/include/QtGui/5.12.10 -I/home/ai/Qt/5.12.10/gcc_64/include/QtGui/5.12.10/QtGui -I/home/ai/Qt/5.12.10/gcc_64/include/QtGui -I/home/ai/Qt/5.12.10/gcc_64/include/QtQml -I/home/ai/Qt/5.12.10/gcc_64/include/QtNetwork -I/home/ai/Qt/5.12.10/gcc_64/include/QtCore/5.12.10 -I/home/ai/Qt/5.12.10/gcc_64/include/QtCore/5.12.10/QtCore -I/home/ai/Qt/5.12.10/gcc_64/include/QtConcurrent -I/home/ai/Qt/5.12.10/gcc_64/include/QtCore -I.moc -isystem /usr/include/libdrm -isystem /usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/home/qt/openssl-1.1.1g/include -I/home/ai/Qt/5.12.10/gcc_64/mkspecs/linux-g++ -o .obj/main.o main.cpp
main.cpp: In function ‘int main(int, char**)’:
main.cpp:27:14: error: ‘class QDeclarativeVideoOutput’ has no member named ‘videoSurface’
     p.vo(vo->videoSurface());
              ^~~~~~~~~~~~

**Comment by valbok** [comment]
great, videoSurface() exists after 5.15.

So it would hard to render in 5.12, it would need custom quick item.

**Comment by ElderOrb** [comment]
Actually 'QAbstractVideoSurface' seems to exist in 5.12 too (and set via setProperty into 'QDeclarativeVideoRendererBackend') so it theory it should be possible to access it, right? The only issue is that it is not created automatically on creation QDeclarativeVideoOutput (createBackend is not called in a constructor in 5.12). But in theory if I find the way to access that property, should be possible, right?

**Comment by valbok** [comment]
great, pushed to master an example:

    class Source : public QObject
    {
        Q_OBJECT
        Q_PROPERTY(QAbstractVideoSurface *videoSurface READ videoSurface WRITE setVideoSurface)
    public:
      
        QAbstractVideoSurface* videoSurface() const { return m_surface; }
        void setVideoSurface(QAbstractVideoSurface *surface)
        {
            m_surface = surface;
        }
  
        QAbstractVideoSurface *m_surface = nullptr;
     };

     Source src;
     vo->setSource(&src);
     if (src.m_surface)
        p.vo(src.m_surface);

**Comment by valbok** [comment]
5.12 is supported now.

**Comment by ElderOrb** [comment]
Just checked - works on ubuntu 18.04 (wsl) with 5.12.10! Thanks!
