### ISSUE TITLE
Build fail 6.4

### ISSUE THREAD

**Issue by valbok** [valbok/QtAVPlayer#378]
![image](https://github.com/valbok/QtAVPlayer/assets/1194376/6b1c9b74-bd64-4b61-b5ed-2ce396848a1c)

**Comment by TyrasNistru** [comment]
It also does not build on Qt 6.5.2, it tries to include a file that doesn't exists on 6.5.2:

`..\..\..\..\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11.cpp(15): fatal error C1083: Cannot open include file: 'private/qwindowsiupointer_p.h': No such file or directory`

**Comment by valbok** [comment]
> It also does not build on Qt 6.5.2, it tries to include a file that doesn't exists on 6.5.2:
> 
> `..\..\..\..\Projects\Labs\QtMultimediaLab\QtAVPlayer\qavhwdevice_d3d11.cpp(15): fatal error C1083: Cannot open include file: 'private/qwindowsiupointer_p.h': No such file or directory`

https://github.com/valbok/QtAVPlayer/pull/391

**Comment by valbok** [comment]
It really fails on 6.4, but works in 6.5.
