### ISSUE TITLE
Does not compile with Qt 6.8.0 

### ISSUE THREAD

**Issue by djeneralstab** [valbok/QtAVPlayer#491]
Qt 6.8.0
MinGW 13.1.0 64-bit
Windows 10

Compile error:
```
..\..\..\..\src\QtAVPlayer\qavvideoframe.cpp:18:10: fatal error: QtMultimedia/private/qabstractvideobuffer_p.h: No such file or directory
   18 | #include <QtMultimedia/private/qabstractvideobuffer_p.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
mingw32-make[1]: *** [Makefile.Debug:2655: debug/qavvideoframe.o] Error 1
```

**Comment by valbok** [comment]
https://github.com/valbok/QtAVPlayer/pull/492
